name: Build Executable

on:
  push:
    branches: [ "main" , "local"]
  pull_request:
    branches: [ "main" , "local"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11  # Replace with your desired Python version

    - name: Install project dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Create Executable
      run: |
        pip install pyinstaller
        pyinstaller --onefile your_script.py

    - name: Upload Executable
      uses: actions/upload-artifact@v2
      with:
        name: executable
        path: dist/  # This is where the executable is stored

    - name: Cleanup
      run: |
        deactivate  # Deactivate the virtual environment
        rm -rf venv  # Remove the virtual environment
