# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" , "local"]
  pull_request:
    branches: [ "main" , "local"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      # Runs a single command to check the style of source code
      - name: Setup
        run: pip install .
      
      # Pip install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          
      # Runs a single command to check the style of source code
      - name: Pylint Source Code
        run: pylint src/**/*.py

      # Runs a single command to check the style of test code
      - name: Pylint Test Code
        run: pylint tests/**/*.py
       
      # Runs unittest
      - name: Run Tests
        run: python -m unittest discover